config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root "pages#index"
  # resources :pages
  # resources :nongdo
  # resources :posts
  # namespace :api do
  #   resources :daily_aqis
  #   resources :daily_stats
  #   resources :sites
  # end

  scope "(:locale)", locale: /en|vi/ do
    root "pages#index"
    resources :pages
    resources :nongdo
    resources :posts
    namespace :api do
      resources :daily_aqis
      resources :daily_stats
      resources :sites
    end

    devise_for :admins, controllers: {
      sessions: 'admins/sessions',
      passwords: 'admins/passwords'
    }

    resources :public
    resources :about
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :admin
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @post = Post.new
    @posts = Post.all.order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_admin.posts.build post_params
    @post.save
    redirect_to posts_path
  end

  def show
    @post = Post.find_by id: params[:id]
  end

  def edit
    @post = Post.find_by id: params[:id]
  end

  def update
    @post = Post.find_by id: params[:id]

    @post.update_attributes post_params
    redirect_to posts_path
  end

  def destroy
    @post = Post.find_by id: params[:id]

    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit :title, :content
  end
end

app/views/posts/_form.html.erb
<%= form_for post do |f| %>
  <div class="form-group">
    <%= f.label :title, t(".title") %>
    <%= f.text_field :title, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= f.label :content, t(".content") %>
    <%= f.cktext_area :content, required: true %>
  </div>

  <div class="actions">
    <%= f.submit t(".post"), class: "btn btn-primary block full-width m-b" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="row news-item">
  <div class="col-sm-12">
    <article>
      <%= link_to post do %>
        <h2>
          <i class="fa fa-check"></i> <%= post.title %>
        </h2>
      <% end %>
      <div class="byline">
        <span><%= post.created_at.strftime "%b %d %Y" %></span>
        <span>
          <i class="fa fa-clock-o"></i> <%= post.created_at.strftime "%R" %>
        </span>
        <span>
          <%= link_to edit_post_path(post) do %>
            <i class="fa fa-pencil"></i> <%= t ".edit" %>
          <% end if admin_signed_in? %>
          <%= link_to post, method: :delete, data: {confirm: "Are you sure?"} do %>
            <i class="fa fa-trash"></i> <%= t ".delete" %>
          <% end if admin_signed_in? %>
        </span>
      </div>
      <p></p>
      <%= raw post.content %>
      <p></p>
    </article>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10">
      <div class="row">
        <h2><%= t ".edit_post" %></h2>
        <hr/>
        <div class="col-sm-12">
          <%= render "form", post: @post %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<style type="text/css">
	article img{
		width: 100% !important;
		height: auto !important;
	}
</style>

<div class="container">
  <div class="row">
    <div class="col-md-10">
      <div class="row">
        <div class="col-sm-12">
          <%#= render "form", post: @post %>
          <%= link_to t(".create_post"), new_post_path, class: "btn btn-primary block full-width m-b" if admin_signed_in? %>
        </div>
      </div>
      <hr/>
      <% if @posts.any? %>
        <%= render @posts %>
      <% else %>
        <h2><%= t ".no_posts" %></h2>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10">
      <div class="row">
        <div class="col-sm-12">
          <%= render "form", post: @post %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10">
      <%= render @post %>
    </div>
  </div>
</div>