config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root "pages#index"
  # resources :pages
  # resources :nongdo
  # resources :posts
  # namespace :api do
  #   resources :daily_aqis
  #   resources :daily_stats
  #   resources :sites
  # end

  scope "(:locale)", locale: /en|vi/ do
    root "pages#index"
    resources :pages
    resources :nongdo
    resources :posts
    namespace :api do
      resources :daily_aqis
      resources :daily_stats
      resources :sites
    end

    devise_for :admins, controllers: {
      sessions: 'admins/sessions',
      passwords: 'admins/passwords'
    }

    resources :public
    resources :about
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end

end

app/models/location.rb
class Location < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :admin
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/admins/passwords_controller.rb
# frozen_string_literal: true

class Admins::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admins/sessions_controller.rb
# frozen_string_literal: true

class Admins::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/api/daily_aqis_controller.rb
class Api::DailyAqisController < ApplicationController
  def index
    indicator = params[:indicator]
    site_id = params[:site_id]
    # response = open("http://moitruongthudo.vn/public/dailyaqi/#{indicator}?site_id=#{site_id}").read
    response = open("http://hanoiair.de/realtime/api/aqi/ESP_00981122/PM2_5").read
    render json: response
  end
end

app/controllers/api/daily_stats_controller.rb
class Api::DailyStatsController < ApplicationController
  def index
    indicator = params[:indicator]
    site_id = params[:site_id]
    response = open("http://moitruongthudo.vn/public/dailystat/#{indicator}?site_id=#{site_id}").read
    render json: response
  end
end

app/controllers/api/sites_controller.rb
class Api::SitesController < ApplicationController
  def index
    require 'open-uri'
    # http://moitruongthudo.vn/api/site
    response = open("http://hanoiair.de/realtime/api/sites").read
    render json: response
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale

  private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    { locale: I18n.locale }
  end
end

app/controllers/nongdo_controller.rb
class NongdoController < ApplicationController
  def index
    site_id = params[:site_id] || 14
    response = JSON.parse open("http://moitruongthudo.vn/public/dailyaqi/PM2.5?site_id=#{site_id}").read
    @today = response.last
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    site_id = params[:site_id] || 14
    # http://moitruongthudo.vn/public/dailyaqi/PM2.5?site_id=#{site_id}
    response = JSON.parse open("http://hanoiair.de/realtime/api/aqi/ESP_00981122/PM2_5").read
    @today = response.last
    response = JSON.parse open("http://hanoiair.de/realtime/api/sites").read
    @sites = response.map {|e| e["id"]}
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @post = Post.new
    @posts = Post.all.order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_admin.posts.build post_params
    @post.save
    redirect_to posts_path
  end

  def show
    @post = Post.find_by id: params[:id]
  end

  def edit
    @post = Post.find_by id: params[:id]
  end

  def update
    @post = Post.find_by id: params[:id]

    @post.update_attributes post_params
    redirect_to posts_path
  end

  def destroy
    @post = Post.find_by id: params[:id]

    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit :title, :content
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
    def index
        redirect_to root_path(site_id: params[:site_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/_footer.html.erb
<footer id="footer">
    	<!-- <img src="/images/logo-nbe.png" style="height: 20px"> -->
  <%#= image_tag "logo-nbe.png", style: "height: 20px" %>
	<span>Trang web này được xây dựng dưới sự hỗ trợ của Đại Sứ Quán Czech trong khuôn khổ dự án 11-18VN01</span>
</footer>

app/views/layouts/_header.html.erb
<div id="header" class="header navbar navbar-default navbar-fixed-top mynav">
  <!-- begin container -->
  <div class="container-fluid">
    <!-- begin navbar-header -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header-navbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </button>
      <a class="visible-xs btn-map-menu" href="/mobile-map"><i class="fa fa-globe"></i> <%= t ".map" %></a>
      <%= link_to root_path, class: "navbar-brand" do %>
        <!-- <img class="hidden-xs hidden-sm" style="width: 320px" src="/images/logo.png">
        <img class="visible-xs visible-sm" style="height: 48px" src="/images/logo-xs.png"> -->
        <%= image_tag "logo.png", style: "width: 320px;" %>
      <% end %>
    </div>
    <!-- end navbar-header -->
    <!-- begin navbar-collapse -->
    <div class="collapse navbar-collapse" id="header-navbar" style="padding-right: 20px">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to root_path do %>
            <i class="fa fa-home"></i> <%= t ".home" %>
          <% end %>
        </li>
        <li><%= link_to t(".news"), posts_path %> </li>
        <li><%= link_to t(".about"), about_index_path %> </li>
        <li>
          <%= link_to locale: (%i(en vi) - [I18n.locale]).first do %>
            <i class="fa fa-language" aria-hidden="true"></i> <%= t ".change_language" %>
          <% end %>
        </li>
        <% if admin_signed_in? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= t ".welcome" %> <%= current_admin.email %>
            <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to t(".sign_out"), destroy_admin_session_path, method: :delete, data: {confirm: "Are you sure?"} %></li>
            </ul>
          </li>
        <% else %>
          <li>
            <%= link_to t(".sign_in"), new_admin_session_path %>
          </li>
        <% end %>
      </ul>
    </div>
    <!-- end navbar-collapse -->
  </div>
  <!-- end container -->
</div>

app/views/layouts/_metadata.html.erb
<meta charset="utf-8" />
<meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
<meta property="app_domain" content="airsense.vn" />
<meta name="description" content="Airsense.vn cung cấp thông tin về môi trường như AQI, nồng độ tạp chất trong không khí" />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AIRSENSE</title>
    <%= render "layouts/metadata" %>
    <%= favicon_link_tag "favicon.ico" %>
    <%= csrf_meta_tags %>
    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= yield :body_class %> pace-done">
    <%= render "layouts/header" %>
    <div class="content" id="content">
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <% if content_for(:assets) %>
      <%= yield :assets %>
    <% end %>
  </body>
</html>

app/views/pages/index.html.erb
<%= content_for :assets do %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/amcharts/3.21.13/amcharts.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/amcharts/3.21.13/serial.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/amcharts/3.21.13/themes/light.js"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAtArVuBrHkGyTkaNtNMWhAGs_wzbO_rS8"></script>
  <script type="text/javascript">
    var site_id = <%= params[:site_id] || 14 %>;
    $(function(){
      // OLD INDICATOR: var indicators = ['NO2','SO2','CO','PM2.5','PM10','O3'];
      var indicators = ['PM2.5','PM10'];

      $(indicators).each(function(i,val){
        loadHourlyAQI(val);
      })
      var lat = 21.02;
      var long = 105.8;
      initMap(12,lat,long);

      updateAQIColor();
    })
  </script>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-md-5">
      <form>
        <h2 class="stitle" style="margin:6px 0">
          <i class="fa fa-navicon"></i>
          <%= t ".select_location" %></h2>
        <!-- <select name="site_id" class="form-control chosen-select" onchange="this.form.submit()">
          <option value="1">Hoàn Kiếm</option>
          <option value="7">Thành Công</option>
          <option value="8">Tân Mai</option>
          <option value="9">Kim Liên</option>
          <option value="10">Phạm Văn Đồng</option>
          <option value="11">Tây Mỗ</option>
          <option value="12">Mỹ Đình</option>
          <option value="13">Hàng Đậu</option>
          <option value="14" selected="">Chi cục bảo vệ môi trường</option>
          <option value="15">Minh Khai - Bắc Từ Liêm</option>
        </select> -->
        <%#= select_tag :site_id, options_for_select(Location.pluck(:name, :site_id), params[:site_id] || 14), class: "form-control chosen-select", onchange: "this.form.submit()" %>
        <%= select_tag :site_id, options_for_select(@sites),
          class: "form-control chosen-select", onchange: "this.form.submit()" %>
      </form>
      <h4><%= t ".data_on" %> <%= @today["time"] %></h4>
      <div class="row">
        <div class="col-md-6">
          <span class="dailyAQI" id="dailyAQISpan" data-aqi="<%= @today["value"] %>" style="color: rgb(34, 34, 34); background-color: rgb(0, 176, 240);">AQI <%= @today["value"] %></span>
        </div>
        <div class="col-md-6">
          <span class="indicatorAQI">
            <a href="/nongdo/?site_id=<%= params[:site_id] || 14 %>"><%= t ".nong_do" %></a>
          </span>
        </div>
      </div>
      <h4><%= t ".aqi_instruction" %></h4>
      <div class="aqiContainer">
        <div id="indicatorAqiPM2.5" class="indicatorAqi" style="overflow: hidden; text-align: left;"></div>
        <div id="indicatorAqiPM10" class="indicatorAqi" style="overflow: hidden; text-align: left;"></div>
<!--         <div id="indicatorAqiNO2" class="indicatorAqi" style="overflow: hidden; text-align: left;"></div>
        <div id="indicatorAqiSO2" class="indicatorAqi" style="overflow: hidden; text-align: left;"></div>
        <div id="indicatorAqiCO" class="indicatorAqi" style="overflow: hidden; text-align: left;"></div>
        <div id="indicatorAqiO3" class="indicatorAqi" style="display: none;"></div> -->
      </div>
    </div>
    <div class="col-md-7">
      <div id="map-container">
        <!-- Map -->
        <div id="map-canvas" style="position: relative; overflow: hidden;"></div>
        <div class="aqi_indexs hidden-xs">
          <label style="font-size: 10px;font-weight: bold;padding: 0;margin: 0"><%= t ".aqi_map_instruction" %></label>
          <table class="table">
            <tbody>
              <tr>
                <td class="level" style="background-color: #2196F3">____</td>
                <td class="level" style="background-color: #FFEB3B">____</td>
                <td class="level" style="background-color: #FF5722">____</td>
                <td class="level" style="background-color: #F44336">____</td>
                <td class="level" style="background-color: #795548">____</td>
              </tr>
              <tr>
                <td class="leveltext"><%= t ".aqi_map_0" %></td>
                <td class="leveltext"><%= t ".aqi_map_50" %></td>
                <td class="leveltext"><%= t ".aqi_map_100" %></td>
                <td class="leveltext"><%= t ".aqi_map_200" %></td>
                <td class="leveltext"><%= t ".aqi_map_300" %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <div class="aqi_indexs free_aqi_indexs visible-xs">
        <label style="font-size: 10px;font-weight: bold;padding: 0;margin: 0"><%= t ".aqi_table_instruction" %></label>
        <table class="table">
          <tbody>
            <tr>
              <td class="level" style="background-color: #2196F3">____</td>
              <td class="level" style="background-color: #FFEB3B">____</td>
              <td class="level" style="background-color: #FF5722">____</td>
              <td class="level" style="background-color: #F44336">____</td>
              <td class="level" style="background-color: #795548">____</td>
            </tr>
            <tr>
              <td class="leveltext"><%= t ".aqi_map_0" %></td>
              <td class="leveltext"><%= t ".aqi_map_50" %></td>
              <td class="leveltext"><%= t ".aqi_map_100" %></td>
              <td class="leveltext"><%= t ".aqi_map_200" %></td>
              <td class="leveltext"><%= t ".aqi_map_300" %></td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="aqi_desc">
        <h2 class="stitle">
          <i class="fa fa-navicon"></i>
          <%= t ".table_convert_aqi" %>
        </h2>
        <%= render "shared/table_aqi" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_table_aqi.html.erb
<table class="table table-bordered">
  <tbody>
    <tr class="active">
      <th style="width: 100px;"><%= t ".aqi_value" %></th>
      <th><%= t ".evaluate" %></th>
      <th><%= t ".consequence" %></th>
      <th><%= t ".color" %></th>
    </tr>
    <tr>
      <td><%= t ".td11" %></td>
      <td><%= t ".td12" %></td>
      <td><%= t ".td13" %></td>
      <td>
        <label class="color" style="background-color: blue"><%= t ".td14" %></label>
      </td>
    </tr>
    <tr>
      <td><%= t ".td21" %></td>
      <td><%= t ".td22" %></td>
      <td><%= t ".td23" %></td>
      <td>
        <label class="color" style="background-color: yellow;color: #cdcdcd"><%= t ".td24" %></label>
      </td>
    </tr>
    <tr>
      <td><%= t ".td31" %></td>
      <td><%= t ".td32" %></td>
      <td><%= t ".td33" %></td>
      <td>
        <label class="color" style="background-color: orange"><%= t ".td34" %></label>
      </td>
    </tr>
    <tr>
      <td><%= t ".td41" %></td>
      <td><%= t ".td42" %></td>
      <td><%= t ".td43" %></td>
      <td>
        <label class="color" style="background-color: red"><%= t ".td44" %></label>
      </td>
    </tr>
    <tr>
      <td><%= t ".td51" %></td>
      <td><%= t ".td52" %></td>
      <td><%= t ".td53" %></td>
      <td>
        <label class="color" style="background-color: brown"><%= t ".td54" %></label>
      </td>
    </tr>
    <tr>
      <td colspan="4" class="text-center">
        <p>
          <strong>(*)</strong>
          <%= t ".ps" %></p>
      </td>
    </tr>
  </tbody>
</table>